# Generated by Django 5.0.3 on 2024-03-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronicas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='atk_mod',
            field=models.FloatField(),
        ),
    ]
