# Generated by Django 5.0.3 on 2024-03-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronicas', '0002_remove_player_age_alter_character_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dungeon_master',
            field=models.BooleanField(default=False),
        ),
    ]
