# Generated by Django 5.0.3 on 2024-03-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronicas', '0006_alter_player_characters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='characters',
            new_name='character',
        ),
    ]
