# Generated by Django 5.0.3 on 2024-03-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronicas', '0007_rename_characters_player_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='character',
            new_name='have_character',
        ),
    ]
