# Generated by Django 5.0.3 on 2024-03-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronicas', '0009_player_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='have_character',
        ),
    ]
