# Generated by Django 5.0.3 on 2024-03-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronicas', '0010_remove_player_have_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
