# Generated by Django 5.0.3 on 2024-03-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronicas', '0013_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
